name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Wait for tests to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-ci
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: success

      - name: Exit if CI did not succeed
        if: steps.wait-for-ci.outputs.conclusion != 'success'
        run: exit 1

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: "${{ secrets.PYPI_TOKEN }}"
